"""Add devices table.

Revision ID: 07581030b12f
Revises: cec7eaf39fda
Create Date: 2025-10-21 13:48:21.355200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07581030b12f"
down_revision: str | Sequence[str] | None = "cec7eaf39fda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("firmware_version", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("name", name=op.f("uq_devices_name")),
    )
    op.add_column("batteries", sa.Column("device_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_batteries_device_id_devices"),
        "batteries",
        "devices",
        ["device_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_batteries_device_id_devices"), "batteries", type_="foreignkey"
    )
    op.drop_column("batteries", "device_id")
    op.drop_table("devices")
    # ### end Alembic commands ###
