"""Initial revision.

Revision ID: a1e355dcba05
Revises:
Create Date: 2025-10-17 17:39:24.441434

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a1e355dcba05"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
