"""Add batteries table.

Revision ID: cec7eaf39fda
Revises: a1e355dcba05
Create Date: 2025-10-17 18:08:11.499663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cec7eaf39fda"
down_revision: str | Sequence[str] | None = "a1e355dcba05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batteries",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("voltage", sa.Float(), nullable=False),
        sa.Column("residual_capacity", sa.Float(), nullable=False),
        sa.Column("lifespan", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batteries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("batteries")
    # ### end Alembic commands ###
